language: ruby
cache: bundler
rvm: ruby-2.1.2
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - cp .sample.env .env
notifications:
  slack:
    secure: TWlhDWFpPYyTd8syhLf7QqRDmzVcnTJa4m05jsDxzg4FWj+yHInx5DZY+eUWRI0BfVt7sypISR1MlueLybRWzO8sapF4URaY2GeGeJyi9J8UzrsU/01Rt2gZpkX6Su4gEZKQSaLRTwHTaITD6xfa7mb1pwMyLBateGm4INF9Rkg=
branches:
  only:
  - master
