<% PASSWORD_FILE = File.join(RAILS_ROOT, '..', '..', 'shared', 'config', 'dbpassword') %>

development:
  adapter: mysql
  database: CHANGEME_development
  username: root
  password: 
  host: localhost
  encoding: utf8
  
test: &TEST
  adapter: mysql
  database: CHANGEME_test
  username: root
  password: 
  host: localhost
  encoding: utf8
  
staging:
  adapter: mysql
  database: CHANGEME_staging
  username: CHANGEME
  password: <%= File.read(PASSWORD_FILE).chomp if File.readable? PASSWORD_FILE %>
  host: localhost
  encoding: utf8
  socket: /var/lib/mysql/mysql.sock
  
production:
  adapter: mysql
  database: CHANGEME_production
  username: CHANGEME
  password: <%= File.read(PASSWORD_FILE).chomp if File.readable? PASSWORD_FILE %>
  host: localhost
  encoding: utf8
  socket: /var/lib/mysql/mysql.sock

cucumber:
  <<: *TEST