development:
  bucket: dev.workshops.thoughtbot
  access_key_id: AKIAII65CQKEKK72G5QA
  secret_access_key: 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
staging:
  bucket: staging.workshops.thoughtbot
  access_key_id: AKIAII65CQKEKK72G5QA
  secret_access_key: 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
production:
  bucket: thoughtbot-workshops
  access_key_id: AKIAII65CQKEKK72G5QA
  secret_access_key: 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
